# Generated by Django 5.1 on 2024-10-02 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adwaitapp', '0003_rename_technologies_services_technologies_service_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technologies_service',
            old_name='main_services_id',
            new_name='main_services',
        ),
        migrations.RenameField(
            model_name='technologies_service',
            old_name='technologies_id',
            new_name='technologies',
        ),
    ]
