# Generated by Django 5.1 on 2024-10-02 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adwaitapp', '0004_rename_main_services_id_technologies_service_main_services_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technologies_service',
            old_name='main_services',
            new_name='main_service',
        ),
    ]
