# Generated by Django 5.1 on 2024-11-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adwaitapp', '0009_inquiries_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_services',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
