# Generated by Django 5.1 on 2024-11-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adwaitapp', '0010_main_services_seo_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sub_services',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
