# Generated by Django 5.1 on 2024-11-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adwaitapp', '0011_blogs_seo_keywords_sub_services_seo_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='seo_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='main_services',
            name='seo_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sub_services',
            name='seo_keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
