# Generated by Django 5.1 on 2024-11-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adwaitapp', '0012_alter_blogs_seo_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiries',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
