# Generated by Django 5.1 on 2024-11-14 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adwaitapp', '0013_inquiries_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiries',
            name='phone',
        ),
    ]
