# Generated by Django 5.1 on 2024-11-14 22:47

import adwaitapp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adwaitapp', '0014_remove_inquiries_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('country', models.CharField(blank=True, max_length=25, null=True)),
                ('more_info', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=adwaitapp.models.developer_upload_path)),
                ('rate', models.SmallIntegerField(blank=True, null=True)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adwaitapp.departments')),
            ],
        ),
    ]
