# Generated by Django 5.1 on 2024-11-15 00:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adwaitapp', '0016_projectphase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now)),
                ('project_name', models.CharField(max_length=255)),
                ('project_code', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('project_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('status', models.SmallIntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adwaitapp.customers')),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adwaitapp.departments')),
                ('main_service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adwaitapp.main_services')),
                ('project_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adwaitapp.projectphase')),
            ],
        ),
    ]
