# Generated by Django 5.1 on 2024-11-15 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adwaitapp', '0017_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Projects',
        ),
    ]
