# Generated by Django 5.1 on 2024-11-15 00:44

import adwaitapp.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adwaitapp', '0018_rename_project_projects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to=adwaitapp.models.project_upload_path)),
                ('uploaded_at', models.DateTimeField(default=datetime.datetime.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adwaitapp.portfolio')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
