# Generated by Django 5.1 on 2024-11-15 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adwaitapp', '0019_project_uploads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_uploads',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adwaitapp.projects'),
        ),
    ]
