# Generated by Django 5.1 on 2024-11-15 00:56

import adwaitapp.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adwaitapp', '0020_alter_project_uploads_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_developers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now)),
                ('wage', models.FloatField(blank=True, null=True)),
                ('hrs', models.FloatField(blank=True, null=True)),
                ('more_info', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=adwaitapp.models.project_upload_path)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adwaitapp.developers')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adwaitapp.projects')),
            ],
        ),
    ]
